### ISSUE TITLE
Could not select profile even after download successful

### ISSUE THREAD

**Issue by deCodeIt** [sbandur84/Free-OpenVPN-Connect-SCRIPT-for-Linux#1]
You put a lot of effort in making this script.

I tried using this but got an error , maybe in fetching the files.

Even after successfully downloading the profiles when I choose option '1) profiles' it says "No profiles available! Download profiles!".

Kindly look into the issue
Thank you

**Comment by sbandur84** [comment]
Hey, maby You dont have folder write permission. Check please.
My answer wil be quicker.

**Comment by Bitsy-Chuck** [comment]
the download links are outdated.
