### ISSUE TITLE
Problem behind proxy

### ISSUE THREAD

**Issue by Achilles-96** [sbandur84/Free-OpenVPN-Connect-SCRIPT-for-Linux#3]
Hi. I am behind my institute proxy. It shows 'Initialization Sequence Completed' but Internet stops working.

**Comment by buenaventura01** [comment]
Hello,

I am also on an institution public network, and I also get 'Initialization Sequence Completed' but Internet stops working.

**Comment by sbandur84** [comment]
Chhose profile TCP80.
