### ISSUE TITLE
Not connecting 

### ISSUE THREAD

**Issue by pallavbohara** [sbandur84/Free-OpenVPN-Connect-SCRIPT-for-Linux#4]
I executed your script, downloaded profile, selected profile, then I am trying to **2) connect** but it is showing this message 

> INFO: Disconnected from uk1.vpnkeys.com.tcp.1.ovpn

**Comment by sbandur84** [comment]
Do you have admin rights?

**Comment by 280Sloppy** [comment]
Do you have 'openvpn' installed? It can be installed with the 'Install' section.
